name: Crowdin upload

on:
  push:
    branches: [ master ]

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Upload to crowdin
        uses: crowdin/github-action@1.0.18
        with:
          upload_translations: true
          source: src/generated/resources/assets/chaoscraft/lang/en_us.json
          download_translations: false
          translation: "%locale%"
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}